//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNata_Testing.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\QAprojects_TFS_data\\DNata_Testing\\DataScripts\\")]
        public string FOLDERDATASCRIPT {
            get {
                return ((string)(this["FOLDERDATASCRIPT"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\DNata_Testing\\DNBata_Testing\\DNata_Testing\\bin\\Debug\\")]
        public string SCRIPTFOLDER {
            get {
                return ((string)(this["SCRIPTFOLDER"]));
            }
            set {
                this["SCRIPTFOLDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RUN_DNATAODATASOURCETESTINGR01.csv")]
        public string SCRIPTFILE {
            get {
                return ((string)(this["SCRIPTFILE"]));
            }
            set {
                this["SCRIPTFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DNATADATASOURCETESTINGR01.csv")]
        public string FOLDERFILESCRIPT {
            get {
                return ((string)(this["FOLDERFILESCRIPT"]));
            }
            set {
                this["FOLDERFILESCRIPT"] = value;
            }
        }
    }
}
